@startuml Course Page
actor User
participant CoursePage
participant CourseDetailPage
participant WebAPI
database UCredit
database RegKMITL

User -> CoursePage ++ : Open course page
CoursePage -> WebAPI ++ : Get course data
WebAPI -> RegKMITL ++ : Query
return Course data
return Course data
return Show course data
User -> CoursePage ++ : Search course
CoursePage -> WebAPI ++ : Get course data
alt sort by rating
    WebAPI -> UCredit ++ : Query sorted by rating
    Return Filtered courses sorted by rating
    WebAPI -> RegKMITL ++ : Query
    return Combined course data (joined result sorted by rating)
    deactivate UCredit
else without sort by rating
    WebAPI -> RegKMITL ++ : Query
    return Filtered course data
end
WebAPI --> CoursePage -- : Filtered course data
CoursePage --> User -- : Show filtered course data

User -> CoursePage ++ : Click course name to view full detail
CoursePage -> CourseDetailPage --++ : Redirect to course detail page
CourseDetailPage -> WebAPI ++ : Get course detail
WebAPI -> RegKMITL ++ : Get course detail data
return Course detail data
WebAPI -> UCredit ++ : Get course detail data
return Course detail data
return Course detail data
CourseDetailPage --> User -- : Show course detail

User -> CoursePage ++ : Click bookmark button
CoursePage -> WebAPI ++ : New bookmark course
WebAPI -> UCredit ++ : Create bookmark course
return Create bookmark course response
return Create bookmark course response
CoursePage --> User -- : List of bookmarked courses updated

User -> CoursePage ++ : Click show bookmarked course button
CoursePage -> CoursePage ++ : Open bookmarked modal
CoursePage -> WebAPI ++ : Get bookmarked courses
WebAPI -> UCredit ++ : Query bookmarked courses
return List of bookmarked courses
return List of bookmarked courses
CoursePage --> User -- : Show bookmarked courses
deactivate CoursePage
@enduml